{% set name = "dtoolcore" %}
{% set version = "3.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32de6dda319002d41fc8a0b7a8835a1de37d9ca60265bf3416bc57caaba0b9f5

build:
  number: 0
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools_scm
  run:
    - setuptools
    - python >=3.6

test:
  imports:
    - dtoolcore
    - dtoolcore.compare
    - dtoolcore.filehasher
    - dtoolcore.storagebroker
    - dtoolcore.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jic-dtool/dtoolcore
  license: MIT
  license_file: LICENSE.rst
  summary: The dtoolcore project provides a Python API for managing (scientific) data.

  description: |
    The dtoolcore project provides a Python API for managing (scientific) data. 
    It allows researchers to:
    * Package data and metadata into a dataset
    * Organise and backup datasets easily
    * Find datasets of interest
    * Verify the contents of datasets
    * Discover and work with data programatically
  doc_url: https://dtoolcore.readthedocs.io/en/latest/
  dev_url: https://github.com/jic-dtool/dtoolcore

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
    - tjelvar-olsson
