{% set name = "dtoolcore" %}
{% set version = "3.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9002f1872074ec8ae83eaa16eb15f55a016bc3d418b553cdd53c8c5de458ca7c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - setuptools
    - python >=3.6

test:
  imports:
    - dtoolcore
    - dtoolcore.compare
    - dtoolcore.filehasher
    - dtoolcore.storagebroker
    - dtoolcore.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jic-dtool/dtoolcore
  license: MIT
  license_file: LICENSE.rst
  summary: The dtoolcore project provides a Python API for managing (scientific) data.

  description: |
    The dtoolcore project provides a Python API for managing (scientific) data. 
    It allows researchers to:
    * Package data and metadata into a dataset
    * Organise and backup datasets easily
    * Find datasets of interest
    * Verify the contents of datasets
    * Discover and work with data programatically
  doc_url: https://dtoolcore.readthedocs.io/en/latest/
  dev_url: https://github.com/jic-dtool/dtoolcore

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
    - tjelvar-olsson
