{% set name = "dtoolcore" %}
{% set author = "jic-dtool" %}
{% set version = "3.15.0" %}
{% set sha256 = "b7970c0985ea998cc35746fb2b996c6880300e982e82491060cefc5e6c929c6f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - setuptools
    - python >=3.6

test:
  imports:
    - dtoolcore
    - dtoolcore.compare
    - dtoolcore.filehasher
    - dtoolcore.storagebroker
    - dtoolcore.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/{{ author }}/{{ name }}
  license: MIT
  license_file: LICENSE.rst
  summary: 'The dtoolcore project provides a Python API for managing (scientific) data.'

  description: |
    The dtoolcore project provides a Python API for managing (scientific) data. 
    It allows researchers to:
    * Package data and metadata into a dataset
    * Organise and backup datasets easily
    * Find datasets of interest
    * Verify the contents of datasets
    * Discover and work with data programatically
  doc_url: https://dtoolcore.readthedocs.io/en/latest/
  dev_url: https://github.com/{{ author }}/{{ name }}

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
