travis:
  secure:
    BINSTAR_TOKEN: uIYlXIdmfz5YvK2Du10kNIXVpl+zQORr4Dou9gV4YdAANI1oHZyoTBSPA1ST0ljg6XBrauKXDnF1EOFb9notCRZ618f2f/MlFfrRuR3TeQEFbKfRzhzvexLIeMxNu9RjmGRp0m2EItdtENR9wWjjIbXN0XyXtzbgVDhBPOlVS8ukQK06uweoaeJELpOmIsG40Va4cosUr5GUM+N8qLsY3pmUvXOA+GvAiwZQP4WeGKygqTeLv5lSMPUgm5dju3P28i28WhZeXvNPr7rA75EMaB5mvF4UtqJiI6MP+E3rGnncQemHRe4wDlGYH2iaDT/AwjEIzvC/YdLvTmyWZUP2fH4H4yntsG3WegMSFj05ZGNDO/p6ESNjuykkuNSmgcxx5qscDt+KVhZmusIpibYKP729a9CAIw/Q3mYjLOAH9C7TSt/40r/Yr+0iN3mQyvXxrkpRbOSfl1kKWhZTJyW0K0dCH4xgJmJyEEWSbsCJaBxs1tuVBt8CV52xGPiZ5bGjFNvFmjsYTLQGtpEK/0zdnEgU9nhempMVEnYDHlB8zRlMCgp1J7HZdsVMK9JxQP+qIAcfYBShZXgTa4p/TZUBT16YlIzpZXQYZO1JPZK0Pg6pM81LVz6HEyUw8xYrc5DFx8TX+4qbwWlrNZKWG3ZmMPiQfk2ZMZ3dwBojT8iROPg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
